version: '3.4'

services:
  
  catalogdb:
    image: mongo

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Catalog/Catalog.API/Dockerfile


#persistent database using the volumes in mogo database data volumes
#data storage that are outside of the containers and exist on the host file system 
volumes:
  mongo_data: 